### ISSUE TITLE
BaseSettings is not accurately tracking the global defaults

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [funkybob/django-classy-settings#12]
i noticed when trying to extend settings like the authentication backends

**Comment by funkybob** [comment]
Please provide details of where it is incorrect...

**Comment by RonnyPfannschmidt** [comment]
```
from cbs import BaseSettings, apply
from django.conf import global_settings

class BrokenExample(BaseSettings):
    PROJECT_NAME = 'hi'
    @property
    def AUTHENTICATION_BACKENDS(self):
        return super().AUTHENTICATION_BACKENDS + ('xxx',)

class WorkingExample(BaseSettings):
    PROJECT_NAME = 'hi'
    @property
    def AUTHENTICATION_BACKENDS(self):
        return global_settings.AUTHENTICATION_BACKENDS + ('xxx',)



import pytest
@pytest.mark.parametrize('cls', [WorkingExample, BrokenExample])
def test_apply(cls):
    apply(cls, {})
```

**Comment by funkybob** [comment]
BaseSettings should not be tracking global_settings, but the project template default settings.

The idea is for it to act as you would expect for a default project created with the current Django version.

Django still does as it always has, and applies any attributes of the settings module to its settings instance if they pass .isupper()

(also, it's not clear from your comment what the outcome of that code is, or what you feel it ought be)

**Comment by RonnyPfannschmidt** [comment]
i might be misled from prior django_configurations usage, which tracked and included the global defaults in a way that subclasses could easyly use them in inheritance

bascially the base class gave a view of all the defaults and one could use all features of inheritance to handle configuration

**Comment by funkybob** [comment]
As an alternative, I've added GlobalSettings as a class  you can mix in to get all the current default global settings into your class.

Can you please test the current master version and let me know how it goes?

**Comment by RonnyPfannschmidt** [comment]
a potential idea would be something like
```python
from django.conf import global_settings

class GlobalSettingsMixin(object):
    def __getattr__(self, key):
         return getattr(global_settings, key)
```

interaction with inheritance is not clear, it should probably always be right before the Base in the mro
