### ISSUE TITLE
consider providing a cbs/wsgi.py and a cbs-manage command

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [funkybob/django-classy-settings#14]
my idea behind that is to ease providing a django-confiugrations alike workflow
where given a module name, and a class name one could easily create a set up django application

the rough workflow i have in mind for that is

1. import the module
2. obtain the named class
3. apply the class to the modules `__dict__`

in case of wsgi.py that would be done as well,

but in addition there could be a convenience to call a given list of wsgi middlewares 
to help apply details like for example the raven Sentry middleware

it could also be used to deploy apps as wheels where a manage.py would not be part of the normal application installation

**Comment by funkybob** [comment]
I'm not really seeing any benefit here.  Why would anyone want to customise manage.py or wsgi.py when the existing, default versions "just work"?

Set your settings the usual way, decide on the mechanism you want to use for choosing the settings class, and you're done.

I don't see how wheels has anything to do with the presence/absence of a projects manage.py.  Even if it's not there, it's just a shim around the same stuff as django-admin... why introduce a customised manage.py that makes you less compatible?

d-c-s is primarily for providing mechanism, not policy.  It gives you the tools to use class-based settings, and integrate them with your project how best suits you.

**Comment by RonnyPfannschmidt** [comment]
I see
