### ISSUE TITLE
introduce a cbs.appliedsettings module that applies a DJANGO_CLASSY_SETTINGS env var

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [funkybob/django-classy-settings#15]
the basic ideas is to have a module that does

```
import cbs
import os
cbs.apply(os.environ['DJANGO_CLASSY_SETTINGS'], globals())
```

**Comment by funkybob** [comment]
I've tried to be deliberately minimalist with this project... this looks like it would move the settings control from DJANGO_SETTINGS_MODULE [which I assume would now become 'cbs.appliedsettings'] to DJANGO_CLASSY_SETTINGS...

Let me sleep on it...

**Comment by RonnyPfannschmidt** [comment]
the thing is, the common django commands expect a configured settings module,
its hard to just integrate, in particular in existing projects or when just reusing deploying things

**Comment by funkybob** [comment]
And they still get one... DJANGO_SETTINGS_MODULE doesn't go away... it should be the module that ends up calling cbs.apply, after deciding which settings mode to use.

**Comment by RonnyPfannschmidt** [comment]
true
