### ISSUE TITLE
Add helpers for complex settings

### ISSUE THREAD

**Issue by funkybob** [funkybob/django-classy-settings#18]
both DATABASES and CACHES require complex settings structures, being lists of dicts of ....

Provide some helpers for handling this, like URL based solutions.

(Templates, too)

**Comment by funkybob** [comment]
@MarkusH i believe you had something to contribute to this?

**Comment by MarkusH** [comment]
Yes, I do, @funkybob. Here are `as_list` and `as_tuple` converters.

**Comment by MarkusH** [comment]
Looking at [django-configurations](https://github.com/jazzband/django-configurations/blob/master/configurations/values.py#L316) I might as well just add an alias `cbs.utils.evaluate = ast.literal_eval`

**Comment by funkybob** [comment]
Yes, but we're trying to encourage _good_ practices here :)
