### ISSUE TITLE
Travis CI not testing on OSX

### ISSUE THREAD

**Issue by tysonclugg** [funkybob/django-classy-settings#23]
I tried changing the Travis config to include OSX, the results were an epic fail (https://travis-ci.org/funkybob/django-classy-settings/builds/93453032).

We could do what pyca/cryptography have done in their [`travis.yml`][yml] ,
or we could wait until [Travis CI issue #2312][2132] is resolved.

@funkybob, which would you prefer?

[yml]: https://github.com/pyca/cryptography/blob/master/.travis.yml
[2132]: https://github.com/travis-ci/travis-ci/issues/2312

**Comment by funkybob** [comment]
Since I've had no complaints yet from the numerous people using this on osX, and it's a pure python project, I see no pressure to enable mac testing.

This can wait until Travis get this shit together.
