### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by mbaechtold** [funkybob/django-classy-settings#29]
Just wanted to let you know that the tests are failing on the master branch: https://travis-ci.org/funkybob/django-classy-settings

**Comment by funkybob** [comment]
Yeah.. that's only for a deprecated "feature", so I'll remove it.
The rest of the noise is py2, which is no longer supported.

Expect to see a 2.1 release later today!

**Comment by mbaechtold** [comment]
Thank you for the release and clarifying the docs 👍
