### ISSUE TITLE
Remove django dependency

### ISSUE THREAD

**Issue by yourcelf** [funkybob/django-classy-settings#34]
Despite the name, this project really doesn't have anything in it that depends on Django other than the `context_processors` and tests.  This library _could_ be just as useful with other frameworks if settings are needed (flask, FastAPI, etc).

It would be great if the django dependency could be changed to be dev-only dependency for the test harnesses.  For projects that don't use/need `context_processors`, the rest of the library would still work perfectly well without django.  Any project needing `context_processors` would surely already have django installed anyway.

**Comment by funkybob** [comment]
You make a good point... however, have you seen my other project https://github.com/funkybob/confucius ?

**Comment by yourcelf** [comment]
Very intriguing! Thanks.

**Comment by funkybob** [comment]
I keep telling myself I'll write a related lib to provide useful parser functions for Confucius to support Django config objects.
