### ISSUE TITLE
DJANGO_MODE var

### ISSUE THREAD

**Issue by amirreza8002** [funkybob/django-classy-settings#47]
hello, thanks for your work!
i wanted to ask if it's possible to use a `.env` file to set the DJANGO_MODE env variable, instead of setting it in the terminal?
and if it is not, can we have it? :)
it would make keeping a consistant development and production env easier

**Comment by amirreza8002** [comment]
hi again @funkybob 
i think what i'm asking can be done with a few lines of code

there is already an `env` parameter in the `use()` method
i can extend the `get_settings_instance` method so it can use the `os.getenv()` or use a library such as `django-environ` depending on the value of `env` argument.

i'm thinking about getting the path to the file as argument, instead of a bool, to make it more costumizable
also i see that django-environ is already used in many projects so it can be a safe option to use, but if you want you can only have it as an optional dependency, i leave that to you to decide 

if you are ok with it, i can code it and send a pull request.
let me know what you think

**Comment by funkybob** [comment]
I'm always happy for people to write PRs :)

I think you misunderstood what I was proposing. The new argument could be _either_ a bool (to use the default filename), _or_ a path to the file to use. So we're pretty much in agreement there :)

**Comment by funkybob** [comment]
Upon further contemplation, I think the best approach here is to document how this can be cleanly achieved, rather than specifically endorse any one solution.

I do appreciate and thank you for your efforts to contribute.
